- topology.go
- topology_linux.go
The root of the segfault was doing an append() on a pre-sized array, but
in diagnosing that issue, I noted that the parsing of sysfs files that
contained cache type, cache size and the shared logical processor map
was improperly leaving newline characters in the resulting []byte that
were read from the sysfs files, resulting in incorrect zeroed values.
Closes Issue #11
> Fix broken SMP/NUMA topology cache construction

- topology.go
- topology_linux.go
The root cause of the bug from issue #14 was the same issue from #11.
When processing the NUMA node core_id map from sysfs on Linux, we were
not appropriately removing the trailing newline from the []byte read
from ioutil.Readfile().
This fixes that issue and adds printing of core and cache information
for the TopologyInfo struct.
Closes Issue #14
> Ensure core ID for topology.Node is correct

- block_linux.go
Modifies the way in which we look for disk serial numbers in the symbolic links in `/dev/disk/by-id` so that SATA drives can be identified properly. SATA drives have inconsistent vendor-specific encoding of serial numbers and product names in the "by-id" symbolic links.
Fixes Issue #19
> Fix SATA disk serial number identification

- README.md
Adds lots of documentation and example code to the README explaining how to query PCI device class, vendor, product and subsystem information from the `ghw.PCIInfo` struct.
Close Issue #24
> Document the new PCI module

- README.md
- pci.go
- pci_linux.go
- pci_test.go
Adds a method to `ghw.PCIInfo` that queries a particular PCI device in sysfs and populates a `ghw.PCIDeviceInfo` struct with information about the device at the supplied address.
Issue #26
Issue #24
> implement `PCIInfo.GetDeviceInfo()`

- .travis.yml
- README.md
- ghwc/main.go
- gpu.go
- gpu_linux.go
- gpu_test.go
- main.go
- main_test.go
- pci.go
- pci_linux.go
For now, the `ghw.GPUInfo` struct is fairly simple, containing a single field called `GraphicsCards` which is an array of `ghw.GraphicsCard` struct pointers. Each of those contains a `ghw.PCIDeviceInfo` that can be used to gather information about the graphics card.
Still to do is gather information about the graphics drivers in use and capabilities of GPUs, vGPUs, etc.
Issue #4
> Adds basic GPU module

- README.md
- gpu.go
- gpu_linux.go
- pci.go
- pci_linux.go
- pci_test.go
Makes the following symbol name changes:
* PCIProgrammingInterfaceInfo -> PCIProgrammingInterface
* PCIClassInfo -> PCIClass
* PCISubclassInfo -> PCISubclass
* PCIProductInfo -> PCIProduct
* PCIVendorInfo -> PCIVendor
* PCIDeviceInfo -> PCIDevice
* GetDeviceInfo() -> GetPCIDevice()
This makes these struct and function names consistent with the other
modules in ghw.
Fixes Issue #32
> Remove Info suffix from most PCI structs

- README.md
- cpu.go
- cpu_linux.go
- gpu.go
- gpu_linux.go
- memory_cache.go
- memory_cache_linux.go
- topology.go
- topology_linux.go
* Removes unnecessary typedefs for uint32 on node and processor
* Renames Node -> TopologyNode (Fix Issue #33)
* Makes memory cache sorting deterministic by breaking ties by looking at the cache's first logical processor (Fix Issue #35)
> Topology module fixes

- .gitignore
- Makefile
Ability to track coverage especially since tests are executed against
systems which differ in hardware.
> Add combined package coverage report

- block_linux.go
- cpu_linux.go
- gpu_linux.go
- memory_cache_linux.go
- memory_linux.go
- net_linux.go
- pci_linux.go
- topology_linux.go
> Build tags and file suffixes overlap in fuctionality. For example, a
file called mypkg_linux.go that contained the build tag // +build linux
is redundant.
> In general, when choosing between a build tag or a file suffix, you
should choose a file suffix when there is an exact match between the
platform or architecture and the file you want to include.
[1] https://dave.cheney.net/2013/10/12/how-to-use-conditional-compilation-with-the-go-build-tool
> Removed build tags

- block_linux.go
- block_linux_test.go
Adds specialized parsing for mountpoints in mtab entries that contain
spaces, tabs and newlines. These characters will be encoded as their
octal-to-string representations by the glibc, and we need to decode
these values accordingly.
Issue #45
> Handle newline, tab and space in mtab entry

- Makefile
Added a couple extra checks to run during `test`.  The fmtcheck
target looks the way it does, so returns an error if gofmt were
to reformat code.  Gofmt does not consider this an error.
> Added vet, fmtcheck, and fmt Makefile targets

- README.md
- block.go
- block_linux.go
- block_test.go
Linux hard-codes the block device sector size to 512, and when
determining the total size of a disk, we multiply this 512 hard-coded
number by the value in /sys/block/$device/size.
We were erroneously calculating the block device's size by multiplying
the physical block size returned from
/sys/block/$device/queue/physical_block_size with the value in
/sys/block/$device/size.
Issue #57
> Correct improper Linux block device size calc

- README.md
- block_linux.go
- cpu_linux.go
- memory_cache_linux.go
- path_linux.go
- path_linux_test.go
- topology_linux.go
If a host filesystem has been bind-mounted to a particular directory
within an application container (say, '/host'), we want to inform `ghw`
to use that bind-mount as its root directory when constructing paths to
certain files like /proc/cpuinfo or /etc/mtab.
This patch adds the ability for the user to set the GHW_CHROOT environ
variable to the value of this alternate root mountpoint, allowing `ghw`
to find important files from within an application container that has
bind-mounted a host filesystem.
Issue #56
> Allow overriding root path/bindmount

- README.md
- block.go
- block_linux.go
This PR adds code to also collect:
- which NUMA node a disk is local to (useful when trying to balance IO)
- the disk's bus path (useful when trying to know where to unplug the thing from)
- the disk's model (useful in conjunction with the serial number)
Also fixes a bug where serial numbers would be listed as #unknown instead of being omitted
One downside is we re-read and re-parse the udev db (a small flat file) for each property lookup. I could cache it, but it would make the code uglier. Let me know if you'd like me to.
If you need me to break these out into separate PRs, just let me know.
> Collect more disk information

- block_stub.go
- cpu_stub.go
- gpu_stub.go
- memory_stub.go
- net_stub.go
- pci_stub.go
- topology_stub.go
Not collecting useful information (yet), but at least doesn't break builds for multi-platform projects which include this as a dependency.
> Build on non-linux platforms

- block_linux.go
- gpu_linux.go
- net_linux.go
- path_linux.go
These make no sense on non-linux platforms and wouldn't exist in `*_otherOS.go` files, so remove them now before anybody starts accidentally using them to avoid breaking backwards compat when adding support for other OSes.
> Stop exporting linux-specific paths

- README.md
- ghwc/cmd/net.go
- net.go
- net_linux.go
Adds the ability to query for a NIC's capabilities (as reported via
`ethtool -k <DEVICE>`). The new `ghw.NICCapability` struct can be used
to determine the name of the capability/feature, whether a NIC has the
feature enabled and whether the feature can be turned on/off.
Note that this patch removes the unused and undocumented attributes from the `ghw.NIC` struct:
- Model
- Vendor
- Driver
- BusType
- EnabledFeatures
We may add one or more of the above *back* into the `ghw.NIC` struct at some point in the future if there is demand for them.
Issue #7
> add NIC capabilities to NIC struct

- block_linux.go
- cpu_linux.go
- gpu_linux.go
- memory_cache_linux.go
- memory_linux.go
- net_linux.go
- pci_linux.go
- utils.go
Two primary things are addressed:
1) All places where we were doing defer r.Close() is changed to instead
call defer safeClose(r), with a new safeClose() function providing
stderr output of any errors that occur while calling Close()
2) Clean up the calls to fmt.Fprintf() in cases where were were printing
warning or error messages to stderr. Fprintf() returns (int, error) and
we silence errcheck by doing _, _ = fmt.Fprintf()
Issue #51
> clean up errcheck linter output

- README.md
- gpu.go
- gpu_linux.go
- gpu_test.go
A PCI device, which graphics cards predominantly are, may only be
affined to a single NUMA node, so this changes the GraphicsCard.Nodes
field to GraphicsCard.Node.
Issue #65
> Make GraphicsCard.Node a pointer not array

- cpu.go
- cpu_linux.go
- topology_linux.go
- utils.go
* Deprecates the `ProcessorCore.Id` and `Processor.Id` fields, adding new `ID` fields. The old fields will be removed in 1.0 release
* Deprecates the undocumented `Processors()` function, since the only interface that `ghw` should provide to get processor information should be the `ghw.CPU()` function that returns a `ghw.CPUInfo` struct
Issue #51
> cpu: linter fixes and deprecation warnings

- block.go
- block_linux.go
- block_test.go
- pci_linux.go
- topology.go
- topology_linux.go
- units.go
Lots of linter suggestion fixes around variable and function naming, missing doc comments, type redundancies.
Issue #51
> lint-fixes: block, pci, and topology modules

- gpu_linux.go
Use the new safeIntFromFile() utility method to grab the GPU's NUMA node
index. This removed the need for a couple warning messages which really
shouldn't have been printing out if the GPU's numa_node file contained a
"-1\n" value.
> use safeIntFromFile() for GPU numa node

- Gopkg.lock
- Gopkg.toml
- pci.go
- pci_linux.go
Lock ourselves in the Gopkg.toml to pcidb 0.2.
0.2 release added ID fields, deprecating the Id fields for PCI structs,
so all this patch does is make use of those new ID fields.
Issue #81
> Move to pcidb 0.2

- README.md
- block.go
- block_linux.go
- block_test.go
- cpu.go
- cpu_linux.go
- gpu.go
- gpu_linux.go
- main.go
- memory.go
- memory_cache_linux.go
- memory_linux.go
- net.go
- net_linux.go
- options.go
- path_linux.go
- path_linux_test.go
- pci.go
- pci_linux.go
- topology.go
- topology_linux.go
Each module (CPU(), Memory(), Network(), etc...) now supports calling
the main module constructor with zero or more pointers to WithOption
structs. There is only a single option (the CHROOT value for path
construction) but I've designed it so the system is flexible for future
additional options without needing to change the calling interface.
To specify a chroot override for a particular module, use the
WithChroot() function, like so:
```go
mem, err := ghw.Memory(WithChroot("/host"));
```
Issue #86
> Support specifying options in module constructors

- Gopkg.lock
- Gopkg.toml
- README.md
- pci.go
- pci_linux.go
Brings in support for the pcidb 0.3 library, which is a
backwards-incompatible release of pcidb. This is why you always pin
dependencies on specific tags/releases!
Issue #87
> update to pcidb 0.3

- cmd/ghwc/commands/root.go
This matches the order in which cobra lists the subcommands too.
> ghwc: Lexically sort subcommand invocation in root cmd

- cmd/ghwc/commands/block.go
- cmd/ghwc/commands/cpu.go
- cmd/ghwc/commands/gpu.go
- cmd/ghwc/commands/memory.go
- cmd/ghwc/commands/net.go
- cmd/ghwc/commands/root.go
- cmd/ghwc/commands/topology.go
This makes it possible to actually produce useful output from ghwc on platforms which only implement a subset of ghw's functionality. Right now this is the case for macOS, which so far only supports querying block devices.
> ghwc: Gather only the info required in each subcommand

- net_linux.go
To detect interfaces like :
- veth
- tun
- bridge
- and, Virtio
- etc;
I suggest to capture sys network interface class path contain
'devices/virtual/net' on symlink target.
> correct detection of virtual interfaces on linux

- README.md
- block_linux.go
I add the Virtio BusType for KVM users.
https://www.linux-kvm.org/page/Virtio
> Disk will show up as /dev/vd[a-z][1-9]
> Add Virtio as BusType

- Gopkg.toml
Because howett.net keeps going down :(
See https://github.com/DHowett/go-plist/issues/38
> Use GitHub url for howett.net/plist

- .travis.yml
- Makefile
- README.md
- block.go
- block_linux.go
- bus_type.go
Modifies the `ghw.Disk` struct's `BusType` attribute to be of type `ghw.BusType` instead of `string`. Creates an "enum" of bus types, including a new PCI bus type which will be useful in future patches for auxiliary devices.
Issue #106
> convert ghw.Disk.BusType to enum

- Gopkg.lock
- Gopkg.toml
- README.md
- architecture.go
- block.go
- bus_type.go
- cmd/ghwc/commands/block.go
- cmd/ghwc/commands/cpu.go
- cmd/ghwc/commands/gpu.go
- cmd/ghwc/commands/memory.go
- cmd/ghwc/commands/net.go
- cmd/ghwc/commands/print_util.go
- cmd/ghwc/commands/root.go
- cmd/ghwc/commands/topology.go
- cpu.go
- cpu_linux.go
- gpu.go
- gpu_linux.go
- main.go
- marshal.go
- memory.go
- memory_cache.go
- memory_cache_linux.go
- net.go
- topology.go
- topology_linux.go
- topology_test.go
Adds support for serializing the primary XXXInfo structs in `ghw` as
JSON and YAML.
Each `ghw.XXXInfo` struct now has a `YAMLString()` and `JSONString()`
method that returns a string with the struct's information serialized to
that format.
The `ghwc` client has been enhanced with a `--format` CLI option that
allows users to print the hardware information in human-readable (the
default), JSON or YAML format:
```
[jaypipes@uberbox ghw]$ go run cmd/ghwc/main.go -f yaml memory 2>/dev/null
memory:
supported_page_sizes:
- 1073741824
- 2097152
total_physical_bytes: 25263415296
total_usable_bytes: 25263415296
[jaypipes@uberbox ghw]$ go run cmd/ghwc/main.go -f json memory 2>/dev/null
{"memory":{"total_physical_bytes":25263415296,"total_usable_bytes":25263415296,"supported_page_sizes":[1073741824,20 …
```
> support JSON and YAML serialization

- README.md
- net.go
- net_linux.go
- net_linux_test.go
Fixes a buggy calculation of whether a NIC capability/feature can be
changed. There were two errors in the previous way of parsing the
feature line in the `ethtool -k` output.
The first error was that any line that did not have three parts was
considered non-changeable. This was incorrect, since this:
scatter-gather: off
actually indicates that the feature can be enabled, and the line has two
fields (parts) not three.
The second error was that we were looking for the string "fixed" instead
of what actually appears, which is "[fixed]", like so:
scatter-gather: off [fixed]
This patch corrects these errors and adds a unit test to prevent
regressions.
We also change the field name of `NICCapability.CanChange` to
`NICCapability.CanEnable` since this is more congruent with the existing
field …
> correct calculation of NICCapability.CanChange

- README.md
- utils.go
With this patch, `ghw` now disables printing of warning messages when a
`GHW_DISABLE_WARNINGS` environ variable is set:
```
[jaypipes@uberbox ghw]$ go run cmd/ghwc/main.go memory
WARNING:
Could not determine total physical bytes of memory. This may
be due to the host being a virtual machine or container with no
/var/log/syslog file, or the current user may not have necessary
privileges to read the syslog. We are falling back to setting the
total physical amount of memory to the total usable amount of memory
memory (24GB physical, 24GB usable)
[jaypipes@uberbox ghw]$ GHW_DISABLE_WARNINGS=1 go run cmd/ghwc/main.go memory
memory (24GB physical, 24GB usable)
```
Issue #110
> allow warnings to be disabled

- Gopkg.lock
- Gopkg.toml
otherwise:
```
$ dep ensure
Warning: the following project(s) have [[constraint]] stanzas in Gopkg.toml:
✗  gopkg.in/yaml.v2
However, these projects are not direct dependencies of the current project:
they are not imported in any .go files, nor are they in the 'required' list in
Gopkg.toml. Dep only applies [[constraint]] rules to direct dependencies, so
these rules will have no effect.
Either import/require packages from these projects so that they become direct
dependencies, or convert each [[constraint]] to an [[override]] to enforce rules
on these projects, if they happen to be transitive dependencies.
```
> dep: s/constraint/override/ for transitive dep

- block_linux.go
Sets the drive type to DRIVE_TYPE_ODD (optical disk) when the drive name starts with "sr" on Linux.
> Added Optical drive support for Linux

- Gopkg.lock
- Gopkg.toml
- block.go
- gpu.go
- net.go
- pci.go
With this patch, PCI device information (currently only on the
GPU/GraphicsCard struct) is serialized to JSON and YAML. In order to
prevent outputting all of the nested PCIDB structs, we required a custom
MarshalJSON marshaler for the PCIDevice struct pointer that only outputs
the ID and name of the vendor, product, class and subsystem instead of
all the vendor's subproducts, etc.
```
[jaypipes@uberbox ghw]$ go run cmd/ghwc/main.go gpu -fyaml
gpu:
cards:
- address: "0000:03:00.0"
index: 0
pci:
address: "0000:03:00.0"
class:
id: "03"
name: Display controller
product:
id: 1c82
name: GP107 [GeForce GTX 1050 Ti]
programming_interface:
id: "00"
name: VGA controller
subclass:
id: "00"
name: VGA compatible controller
subsystem:
id: "8613"
name: unknown
vendor:
id: 10de
name: NVIDIA Corporation …
```
> Adds JSON/YAML serialization for PCI device info

- cpu.go
- doc.go
- main.go
Adds a doc.go module with long-form developer documentation, mostly
taken from the README but without the struct field descriptions. I've
added CPU-specific struct field descriptions to the cpu.go module and
want to see how this all looks when the documentation is rendered on
https://godoc.org/github.com/jaypipes/ghw.
Issue #72
> godoc-ify the CPU module and add doc.go

- block_linux.go
The current parser ignores `/dev/xvd*` block devices :( this should fix it
> Added support for parsing AWS xvd prefixed block devices

- block_darwin.go
This is a situation that happened on a:
Darwin MacBook-Pro.local 18.7.0 Darwin Kernel Version 18.7.0:
Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64
func (ctx *context) getIoregPlist(ioDeviceTreePath string) (*ioregPlist, error)
Can get an argument value of "IODeviceTree:/". This means that it shells
out to ioreg like this: "ioreg -a -d 1 -r -n IODeviceTree:"
It gives back no output. This should handle that case.
> Case where ioreg returns zero-length output

- go.mod
- go.sum
Updates go.mod dependency on github.com/jaypipes/pcidb to v0.5.0 release
> Use semver v0.5.0 pcidb release

- block_linux.go
- block_test.go
Due to the way the `ctx.partitionSizeBytes` method was attempting to
determine the disk name by examining the partition name, we were not
properly handling MMC/SD drives. This patch resolves this issue by
moving the regex handling for determining disk names from a single
partition name string into the (deprecated in 0.2)
`ghw.PartitionSizeBytes` function and doing some string prefix matching
that handles all known disk types, including MMC/SD. This is no longer
necessary for the `ctx.partitionSizeBytes` method since this method now
takes the disk name and partition name as separate arguments.
Closes Issue #139
> Fix partitionSizeBytes for MMC/SD block devices

- .travis.yml
- block_test.go
- dmi_stub.go
The dmiFillInfo() function was removed when refactoring the original
patch for DMI, leaving only a dmiItem() function. This patch references
that dmiItem() function from the dmi_stub.go file, fixing builds on
MacOSX.
Closes Issue #145
> clean up dmi stub

- Dockerfile
- cmd/ghw-snapshot/main.go
- hack/run-against-snapshot.sh
Issue #66 
Adds a new `ghw-snapshot` binary that creates a tarball containing
a static filesystem snapshot of the various pseudofiles in sysfs that
describe CPU, memory and block devices. A hack/run-against-snapshot.sh
script is included that builds the ghwc binary into a Docker image,
extracts a snapshot created by ghwc-snapshot into a tmpdir, and
runs the ghwc Docker image after bind-mounting the snapshot tmpdir
as /host.
This allows us to test ghw against a snapshot static filesystem from a
user's machine (Linux only for now)
Still remaining to do is include in the snapshot filesystem information
about graphics cards, NICs and udev database entries.
> utility for generating static filesystem snapshot

- block_stub.go
- block_windows.go
- go.mod
- go.sum
Added partial windows support to block
Issue #8
> Windows support: block

- go.mod
- go.sum
- net_stub.go
- net_windows.go
Added partial windows support to net
Issue #8
> Windows support: net

- block_linux.go
- cmd/ghw-snapshot/main.go
- hack/run-against-snapshot.sh
- topology_linux.go
- utils.go
Adds information about disk partitions to the static filesystem snapshot
constructed by `ghw-snapshot` by creating the files that `ghw.blockFillInfo()`
ends up querying on Linux. There are still issues, however, with Docker not
respecting symlinks in host-mounted directories, which results in failure to
determine partition information properly:
```
jaypipes@thelio:~/go/src/github.com/jaypipes/ghw$ ./hack/run-against-snapshot.sh linux-amd64-2f07bdc5e6c060b2ad2f6c65799544fa.tar.gz 
extracting snapshot linux-amd64-2f07bdc5e6c060b2ad2f6c65799544fa.tar.gz to /tmp/ghw-snap-test-QhB ...
building Docker image with ghwc ...
<snip>
running ghwc Docker image with volume mount to snapshot dir ...
WARNING: failed to read int from file: open /host/sys/block/nvme0n1/queue/rotational: no such file or …
```
> add partition information to snapshot

- cmd/ghw-snapshot/main.go
This fixes a dropped `err` variable in `cmd/ghw-snapshot`.
> cmd/ghw-snapshot: fix dropped error

- .travis.yml
If now is the time, here is an update to `.travis.yml` to test against Go 1.14.x.
> Update travis to test go1.14

- memory.go
- memory_windows.go
When collecting HW informations about memory, it's also very useful to
know the physical memory banks and their specs
> Feature: Memory Banks (Windows Only)

- block_windows.go
The Win32_DiskDrive.MediaType field apparently is not reliable for
having "fixed" or "ssd" in it for anything prior to Windows 8, so the
recommended "solution" to determine SSDs for Windows is to also look in
the Win32_DiskDrive.Caption field for the string "ssd".
We also remove whitespace from the caption/name fields for partitions
and block devices on Windows.
Fixes Issue #177
> [windows] look in diskdrive.Caption for "ssd"

- README.md
- block.go
- block_windows.go
Removes the /dev prefix of a `ghw.Disk` when printing to stdout. Also
sets the physical block size for the disk on Windows (retrievable via
the `Win32_DiskDrive.DefaultBlockSize` field) for Windows disk drives.
Issue #165
> [block] remove unnecessary /dev prefix in Windows

- README.md
There has been some confusion about what the difference between physical
and usable RAM is and why `ghw` doesn't report transient metrics like
available/used RAM. This patch adds some documentation explaining both.
Issue #185
> Add documentation about Physical vs Usable RAM

- baseboard_windows.go
- bios_windows.go
- block_windows.go
- chassis_windows.go
- cpu_windows.go
- memory_windows.go
- net_windows.go
- product_windows.go
The github.com/StackExchange/wmi package is great, but handles nil
results from the WMI/WQL call *only* if the type in the receiving struct
is a pointer type:
https://github.com/StackExchange/wmi/blob/cbe66965904dbe8a6cd589e2298e5d8b986bd7dd/wmi.go#L420-L426
So, for various fields (all strings that I can gather so far) that on
*some* systems return nil type from WMI, I've made the fields in the
receiver structs *string instead of string. This should allow nil-types
to be properly handled and not run into the `unsupported type (<nil>)`
issue faced in Issue #189
Closes Issue #189
> [windows] handle nil strings in WMI output

- block_windows.go
- memory_windows.go
- net_windows.go
Apparently WMI will return `<nil>` type even for integer fields like
DefaultBlockSize :(
Issue #189
> use all pointer types for receiving fields in WMI

- .gitignore
- topology_stub.go
- topology_windows.go
Adds a `ghw.TopologyInfo` implementation for Windows that uses the
Win32 GetLogicalProcessorInformation API call. This first batch simply
implements NUMA node construction for each identified NUMA node in the
returned logical processor information struct array. Next patches will
implement the cache discovery mechanisms.
Issue #166
> [windows] find processor topology info

- pkg/block/block_windows.go
- pkg/cpu/cpu_windows.go
- pkg/gpu/gpu_windows.go
- pkg/memory/memory_windows.go
- pkg/pci/pci_stub.go
- pkg/topology/topology_windows.go
There were some typos and package renames that messed up on Windows for
the pkg-cleanup commits. This fixes them all and gets Windows back
working.
> Correct issues on Windows with pkg cleanup

- pkg/linuxpath/path_linux.go
- pkg/memory/memory_linux.go
This PR allows to first determine on Linux systems the total of physical memory from sysfs (`/sys/devices/system/memory`) as primary method and fallback to syslog file method if `/sys/devices/system/memory` is not present for some reasons
> Determine total physical memory from sysfs for linux as primary method

- README.md
- SNAPSHOT.md
- hack/run-against-snapshot.sh
GHW gained support to consume snapshot programmatically.
This means there is no need anymore to expand the snapshot before
mount it in docker, which greatly simplifies the
`run-against-snapshot.sh` scripts.
We just need to pass the snapshot and a bunch of environment variables.
Additionally, start document describing how a GHW compliant snapshot
should look like, and why things are the way they are.
> hack: expand snapshots inside docker

- pkg/option/option_test.go
Add missing test for `pkg/option`. This is especially relevant since commit 1a9fae71d9ffda99c99afdab8b96e0fba708945d added quite few changes to the `option` package. We aim for minimal coverage here, and we will iterate later on expanding the coverage.
> pkg: option: add basic unit tests

- README.md
- cmd/ghwc/commands/pci.go
- host.go
- pkg/pci/pci.go
- pkg/pci/pci_linux.go
Adds a new `ghwc pci` subcommand that lists PCI devices. Deprecates the
old PCIInfo.Products, PCIInfo.Classes and PCIInfo.Vendors maps because
these are now fully contained in the github.com/jaypipes/pcidb library.
```
[jaypipes@thelio ghw]$ go run cmd/ghwc/main.go pci
PCI (45 devices)
[jaypipes@thelio ghw]$ go run cmd/ghwc/main.go pci --format yaml | head -n30
pci:
Devices:
- address: "0000:00:00.0"
class:
id: "06"
name: Bridge
product:
id: "1450"
name: Family 17h (Models 00h-0fh) Root Complex
programming_interface:
id: "00"
name: unknown
subclass:
id: "00"
name: Host bridge
subsystem:
id: "1450"
name: unknown
vendor:
id: "1022"
name: Advanced Micro Devices, Inc. [AMD]
- address: "0000:00:00.2"
class:
id: "08"
name: Generic system peripheral
product:
id: "1451"
name: Family 17h (Models …
```
> add PCI device info to ghwc

- pkg/pci/pci.go
- pkg/pci/pci_linux.go
- pkg/pci/pci_test.go
PR https://github.com/jaypipes/ghw/pull/209 exposed a mashalling issue with some devices.
The issue is the quoting of " from the description of some devices (e.g. 2.5" device).
Add a test to demonstrate the bug and a possible fix.
> pci: JSON device marshalling fixes

- pkg/pci/pci.go
Caught just running "make" on my local tree. I wonder why CI didn't catch it earlier.
> pci: fix typo in struct declaration

- pkg/pci/pci.go
- pkg/pci/pci_linux.go
- pkg/pci/pci_test.go
Providing access to the revision number of hardware can be useful in
identifying or diagnosing problems introduced across versions of single
product line.
Signed-off-by: Kevin Pearson <kevin.pearson@ortmanconsulting.com>
> PCI: Add device revision number

- pkg/block/block_linux.go
Some systems don't have an ID_SERIAL_SHORT value. In these cases,
instead of returning UNKNOWN, let's fall back to ID_SERIAL.
Issue #213
> fall back to ID_SERIAL if ID_SERIAL_SHORT missing

- README.md
- alias.go
- host.go
- pkg/baseboard/baseboard.go
- pkg/bios/bios.go
- pkg/block/block.go
- pkg/block/block_linux.go
- pkg/chassis/chassis.go
- pkg/context/context.go
- pkg/cpu/cpu.go
- pkg/cpu/cpu_linux.go
- pkg/gpu/gpu.go
- pkg/gpu/gpu_linux.go
- pkg/linuxdmi/dmi_linux.go
- pkg/marshal/marshal.go
- pkg/memory/memory.go
- pkg/memory/memory_linux.go
- pkg/net/net.go
- pkg/net/net_linux.go
- pkg/option/option.go
- pkg/pci/pci.go
- pkg/pci/pci_test.go
- pkg/product/product.go
- pkg/topology/topology.go
- pkg/topology/topology_linux.go
- pkg/util/util.go
This PR wants to solve https://github.com/jaypipes/ghw/issues/175
This patch add support for a new option, which allow
the caller code to pass a new Alerter to ghw.
`Alerter` is a dead-simple interface, supporting only a
`Printf` method much like the stdlib `log` package.
ghw will send all the warnings to this method.
We use a so simple interface because we want to generalize a bit
the existing `util.Warn` concept, but is not clear if ghw will benefit
of a more complete logging interface; should that be the case, we
can build on the concept we laid in this patch.
Client code can programmatically override the Alerter, or
users can using the faimiliar `GHW_DISABLE_WARNINGS` environ variable,
which keep functioning as usual.
ghw can be configured to swallow all the warnings or to keep …
> warning: support new option to override default

- pkg/pci/pci.go
- pkg/pci/pci_linux.go
- pkg/pci/pci_test.go
We have AddressFromString(), so it seems natural to add
the symmetric, which we can also use in few places internally
to make the code more readable.
> pci: add String() method to pci.Device

- pkg/net/net.go
- pkg/net/net_linux.go
Report the backing device address - currently PCI only -
in the network interface data.
This allows the client code to fetch the device information using
the specific package, for example `pkg/pci`.
We prefer to add the address, and not a pointer to the relevant
backing device object, the make the net module less coupled with
the other hardware modules.
> pkg: net: report backing device address

- README.md
Document the new field added in commit 13f3f64
> doc: README: document the net.NIC.PCIAddress

- README.md
- alias.go
- pkg/context/context.go
- pkg/net/net_linux.go
- pkg/option/option.go
- pkg/option/option_test.go
- pkg/snapshot/clonetree.go
- pkg/snapshot/clonetree_net.go
This is more prep work for collecting SRIOV-related data (https://github.com/jaypipes/ghw/issues/92). We want to make sure that:
1. we don't confuse users with informations gathered by tools when reading back from snapshots, allowing them to opt-out from `ethtool` and other tools
2. we want to make sure to collect data related to network interfaces.
> snapshot: initial support to collect data pertaining to network interfaces

- README.md
- pkg/snapshot/clonetree_net.go
Some spelling error sneaked in alongside https://github.com/jaypipes/ghw/pull/227
Let's fix them.
> fix spelling/grammar mistakes

- pkg/pci/pci_linux.go
- pkg/pci/pci_linux_test.go
Strip unnecessary whitespaces from the pci.Device.Revision field.
Add unit test to allow to catch up these errors in the future.
> pci: fix revision reporting

- alias.go
- pkg/pci/address/address.go
- pkg/pci/address/address_test.go
- pkg/pci/pci.go
- pkg/pci/pci_linux.go
- pkg/pci/pci_test.go
- pkg/snapshot/clonetree.go
- pkg/snapshot/clonetree_net.go
- pkg/snapshot/clonetree_pci.go
the current implementation of the PCI device snapshot only scans the first level in the PCI tree (actually, PCI forest). Anything attached to bridges is ignored. This was unintended, and this PR aims to fix it acknowledging bridges explictely and handling them correctly. In practices, this means to scan also the devices attached to each bridge, recursively.
Note this affects only the snapshotting code.
> snapshot: gather full pci tree, handling bridges

- pkg/gpu/gpu_test.go
- pkg/memory/memory_cache_linux.go
- pkg/snapshot/clonetree_block.go
- pkg/snapshot/pack.go
- pkg/snapshot/unpack_test.go
Reading the documentation of `os.IsNotExist` and similar functions
(see https://golang.org/pkg/os/#IsNotExist), we learn that
```
This function predates errors.Is. It only supports errors returned
by the os package. New code should use errors.Is(err, os.ErrNotExist).
```
ghw uses these functions but sparsely, so we take the chance
in this PR to modernize the codebase.
No intended changes in behaviour.
> janitorial: modernize error detection

- pkg/snapshot/clonetree_test.go
- pkg/snapshot/pack_test.go
Errors in the tests caused leaks of unpacked test directory.
Make sure to clean up after ourselves.
> test: snapshot: don't leak unpack directory

- README.md
Previously the documentation claimed the snapshot support code
could clean up properly when `GHW_SNAPSHOT_ROOT` is given.
This is too risky to be done safely, and having shared ownership
(client code owns the directory, ghw owns _some_ of its content)
is a bad idea anyway.
Thus, better not to attempt half-baked work: ghw will leave the
GHW_SNAPSHOT_ROOT directory alone completely.
Please note this also reflects what the code actually does
and the intention expressed in the comment in `pkg/context/context.go`
> doc: don't claim we clean up user-supplied dirs

- pkg/pci/pci.go
- pkg/pci/pci_linux.go
Add a simple helper to find a device among the `pci.Info.Devices`.
Up until now, client code had to reimplement the find function
every time, or to call `GetDevice`. Problem is:
`GetDevice`  access the system every time.
In most cases, besides a tiny performance hit, this is no issue.
When consuming snapshots, however, this may lead to surprising behaviour
because the caller need to ensure the snapshot is available when
`GetDevice` is called, or it will return unpredictable result (!!!).
The wrong code looks like that:
1. PCI info is created supplying snapshot data with automatic management
1.a ghw unpacks the snapshot on a temporary dir
1.b ghw loads all the info from the snapshot. info.Devices contains
correct data
1.c ghw cleans up the snapshot (see: …
> pci: add and use LookupDevice

- pkg/context/context.go
- pkg/context/context_test.go
Fix an error preventing the auto-unpacked snapshot files to be deleted.
Add a unit-test to expose the issue.
Signed-off-by: Marcel Apfelbaum <marcel@redhat.com>
> context: Fix directory leakage for snapshots contexts

- pkg/gpu/gpu_linux.go
- pkg/pci/pci.go
The GPU package uses the pci and the topology packages internally.
Make sure to pass to them the same context the package is using,
in order to ensure more consistent behaviour, enable snapshot
consumption - and to waste a little less work in general.
> gpu: pass through the context into subsystems

- pkg/snapshot/clonetree.go
- pkg/snapshot/clonetree_gpu.go
- pkg/snapshot/clonetree_net.go
make sure the snapshot code collects data related to GPU devices.
Turns out not much was missing, most notably the `/sys/class/drm` link;
nevertheless, let's make sure to collect this data, so now also the
gpu package can consume snapshots.
We choose to refactor the code from net devices collection more
for clarity -what we collect and what we filter out is a bit more
explicit now- than to avoid duplication.
The PCI collection code is a bit more elaborate, because it needs to
deal with PCI roots and subtrees (subforests?), so it was intentionally
left out for the time being.
> snapshot: collect data related to GPU devices

- README.md
- pkg/pci/address/address.go
- pkg/pci/address/address_test.go
- pkg/pci/pci_linux.go
As noted by @pearsonk in #220, the PCIAddress.Slot field was a bit of a
misnomer, since the more common representation of a PCIAddress is
Bus:Device.Function, not Bus:Slot.Function. Actual PCI slot information
may be retrieved from DMI, but what we were referring to was not the
actual PCI slot information but rather the PCI address device component.
Fixes Issue #220
> rename PCIAddress.Slot to PCIAddress.Device

- README.md
- alias.go
- pkg/context/context.go
- pkg/linuxpath/path_linux.go
- pkg/linuxpath/path_linux_test.go
- pkg/option/option.go
- pkg/option/option_test.go
Inside containers, when granting access to the host file systems, is
common practice to bind-mount specific host subtrees on nonstandard
locations, like `/sys` on `/host-sys` or `/proc` on `/host-proc`.
To better cover this use case, `ghw` allows to *programmatically* override
the initial component of filesystems subtrees, allowing to access `sysfs`
(or `procfs` or...) mounted on these non-standard locations.
> linuxpaths: allow to override mount points

- pkg/pci/pci_linux.go
- pkg/pci/pci_linux_test.go
Add a sanity check against bad modalias data (corrupted/truncated).
Thsi should never happen in practice, but it's a trivial check,
prevents a nasty segfault and looks like the sriov device plugin
checks for this case (https://github.com/k8snetworkplumbingwg/sriov-network-device-plugin/blob/v3.3.2/cmd/sriovdp/manager_test.go#L322)
so let's add it.
> pci: check against corrupted modalias data

- README.md
- pkg/block/block_darwin.go
- pkg/block/block_linux.go
turns out we call external tools in the block subpackage, hence
we need to handle the EnableTools flag we added in commit
591a1bababf9ac1446a13e75ab3cae2df40b9619
> block: honour EnableTools flag

- pkg/block/block.go
- pkg/block/block_test.go
- testdata/samples/dell-r610-block.json
- testdata/testdata.go
The block.Info struct uses a couple of new types which lack
proper UnmarshalJSON  methods, and this prevent to have full
encode/decode/encode cycles (aka roundtrips).
This seems a unnecessary limitation, so this patch adds
the missing functions.
Fixes: https://github.com/jaypipes/ghw/issues/274
> block: allow encode/decode cycle for block.Info

- pkg/context/context.go
- pkg/gpu/gpu_linux.go
- pkg/option/option.go
- pkg/pci/pci.go
- pkg/topology/topology.go
This patch simplifies some internal-only code that was added to ghw to
prevent re-creating Context objects inefficiently during snapshot
creation. We add a `context.WithContext` function that returns an
`option.Option` containing a pre-existing `Context` struct pointer,
embedded in the `Option` as a raw `interface{}` to get around package
recursive import issues.
Now, when packages like `pkg/gpu` or `pkg/pci` need to load the
`pkg/topology` package, they call
`topology.New(context.WithContext(ctx))`, passing in the
already-existing `Context` object. This preserves the original `New`
function signature without adding a new `NewWithContext` function
signature to all packages.
Alternative to #278
Signed-off-by: Jay Pipes <jaypipes@gmail.com>
> allow passing in existing Context as an Option

- pkg/pci/pci_linux.go
The snapshot implementation leverages chroot and transparently set it to the unpacked snapshot root. This is the intentional behaviour and ghw supports it.
But the `pci` package passes throu the chroot settings to `pcidb` and the latter doesn't know or care about ghw snapshots - and rightly so!
Hence, we need to pass through the `chroot` setting only if explicitely set by client code - so if no snapshot settings are present.
> pci: don't pass chroot to pcidb with snapshots

- .github/workflows/go.yml
- alias.go
- cmd/ghw-snapshot/main.go
- hack/check-format.sh
- pkg/block/block_linux.go
- pkg/context/context.go
- pkg/gpu/gpu_linux_test.go
- pkg/pci/pci.go
- pkg/pci/pci_linux_test.go
- pkg/snapshot/clonetree_net_linux.go
- pkg/snapshot/pack.go
- pkg/snapshot/trace.go
- pkg/topology/topology_linux.go
- pkg/util/util.go
Add gh actions lane to run static code checks:
- linting provided by `golangci-lint`
- basic code format check using `go fmt`
Fixes: https://github.com/jaypipes/ghw/issues/51
> add lane with static checks

- pkg/net/net_windows.go
This is my proposed fix for #291 .
Simple test with my windows pc, showing `nic.Name` and `nic.IsVirtual`:
```text
Microsoft Kernel Debug Network Adapter                                                  true
VirtualBox Host-Only Network - VirtualBox Host-Only Ethernet Adapter                    false
Ethernet - Realtek Gaming GbE Family Controller                                         false
WAN Miniport (SSTP)                                                                     true
WAN Miniport (IKEv2)                                                                    true
WAN Miniport (L2TP)                                                                     true
WAN Miniport (PPTP)                                                                     true
WAN Miniport (PPPOE) …
```
> Win32_NetworkAdapter: use PhysicalAdapter to check whether the NIC IsVirtual

- pkg/baseboard/baseboard.go
- pkg/block/block.go
- pkg/chassis/chassis.go
- pkg/product/product.go
- pkg/util/util.go
- pkg/util/util_test.go
A relatively common pattern in the ghw codebase
is concatenating quite a lot of strings inside
a format string. This leads to a pattern like '%s%s%s%s%s'
which are hard to read and to debug.
Ad a simple helper to concatenate strings to simplify the
format strings.
This may be the definitive solution here, but
it should improve the maintenability and readability,
and it's very cheap to implement and maintain.
> util: add helper to avoid long format strings

- pkg/block/block_linux.go
- pkg/block/block_linux_test.go
This mainly reuses the udevInfo method to obtain the udev info for a
given partition in a given disk instead of having the label value always
empty.
This separates the udevInfo method into 2 distinct methods, one for disk
and one for partition.
This also opens the possibility of obtaining more info for partitions,
i.e. the FS of an unmounted partition.
Signed-off-by: Itxaka <igarcia@suse.com>
> Get partition labels from udev

- pkg/block/block.go
- pkg/block/block_linux.go
- pkg/block/block_linux_test.go
This reverts commit 3171315ec3b21f49a6d7f61a02c6a6edb46cf843.
We can discuss whether there are merits to `ghw` determining whether a
SCSI storage controller communicates via a local storage bus or via
TCP/IP (iSCSI), but iSCSI is not a new drive type so I'm reverting this
particular commit.
Signed-off-by: Jay Pipes <jaypipes@gmail.com>
> Revert "Detect iSCSI devices"

- pkg/block/block.go
- pkg/block/block_linux.go
- pkg/block/block_linux_test.go
The label entry in the Partition struct should correspond to the
partition label, but we were getting the FS label instead.
This patch fixes that by getting the actual partition label for the
label value and adding an extra field on the Partition struct to add the
fs label, so they are separated and clear on which is which.
Signed-off-by: Itxaka <igarcia@suse.com>
> Fix wrong fs label as partition label

- README.md
Adds missing documentation for new Label and FilesystemLabel fields for
Partition structs.
Signed-off-by: Jay Pipes <jaypipes@gmail.com>
> add docs for Label and FilesystemLabel in README

- README.md
- pkg/block/block_linux.go
- pkg/block/block_linux_test.go
This allows us to drop the use of blkid completely and on linux fully
report all the data rootless.
Closes #319 
Signed-off-by: Itxaka <igarcia@suse.com>
> Use udev for partition UUID

- pkg/pci/pci_linux.go
- pkg/pci/pci_linux_test.go
All class IDs in https://pci-ids.ucw.cz/v2.2/pci.ids are stored as lowercase hex. The `modalias` file is used to extract the class IDs for a given device. The class IDs in that file can be uppercase HEX, e.g. pci:v00008086d00009D23sv00001028sd000007EAbc**0C**sc05i00. PCI DB lookup fails in that case.
**- What I did**
* Made sure that class-related IDs (class, subclass, programming interface) are parsed as lowercase hex.
**- How I did it**
* Using the `strings.ToLower` function on raw data
> Fix class name lookups

- .github/workflows/go.yml
- go.mod
- go.sum
This updates the go.{mod,sum} files to declare a version of Go that supports module graph pruning. The change allows consuming projects to avoid picking up dependencies on modules that ghw only uses for testing or for its CLI.
Fixes #328
Signed-off-by: Chris Waldon <christopher.waldon.dev@gmail.com>
> deps: declare go 1.18 in go.mod

- pkg/gpu/gpu_windows.go
GPU does not currently return driver version for Windows. Adding these 3 lines reliably returns driver version
```
package main
import (
"fmt"
"github.com/jaypipes/ghw"
)
type gpuInfo struct {
Vendor        string
Name          string
OfflineDriver string
}
func GetGpuData() []gpuInfo {
gpus := []gpuInfo{}
cards, err := ghw.GPU()
if err != nil {
fmt.Printf("Error getting GPU info: %v", err)
}
for _, card := range cards.GraphicsCards {
gpu := gpuInfo{
Name:          card.DeviceInfo.Product.Name,
Vendor:        card.DeviceInfo.Vendor.Name,
OfflineDriver: card.DeviceInfo.Driver,
}
gpus = append(gpus, gpu)
}
return gpus
}
func main() {
gpus := GetGpuData()
for _, gpu := range gpus {
println("GPU Vendor: ", gpu.Vendor)
println("GPU Name: ", gpu.Name)
println("Driver: ", gpu.OfflineDriver)
}
} …
```
> added gpu driver query for windows

- pkg/memory/memory_linux.go
`/sys/devices/system/memory` does not exist on linux/arm systems that do not support memory hotplug. This means that the
`/sys/devices/system/memory/block_size_bytes` file also does not exist and that is the file that we use to determine the physical RAM associated with a RAM module affined to a NUMA node.
This commit updates the logic in `pkg/memory.AreaForNode` on linux platforms to tolerate the error returned by `memoryBlockSizeBytes()` when `/sys/devices/system/memory/block_size_bytes` does not exist and set a memory `Area`'s `TotalPhysicalBytes` value to the value of `TotalUsableBytes`.
Issue #336
> assume phys mem == usable mem on ARM

- README.md
- pkg/net/net.go
- pkg/net/net_linux.go
- pkg/net/net_linux_test.go
- pkg/util/util.go
- pkg/util/util_test.go
Make `AutoNegotiation` and `PauseFrameUse` `NICCapability` objects:
* AutoNegotiation (string value of auto-negotiation)
* PauseFrameUse (string value of pause-frame-use)
Refactoring PR #335
> Add AutoNegotiation and PauseFrameUse NICCapabilities

- .github/workflows/go.yml
- doc.go
Brings in Ubuntu 22.04, Windows Server 2022 and MacOS 12 (instead of the now-deprecated <=MacOS-11 runner).
Also updates the Go versions to test Go 1.18-1.20 on various platforms.
> update our GH actions runners/workflows

- pkg/memory/memory_linux.go
The `/sys/devices/system/memory` and `/sys/devices/system/node/nodeX` subdirectories contains one or more subdirectories that begin with the word "memory" and end in a 0-based cell/block index for that memory. e.g. `/sys/devices/system/node/node0/memory63` is a directory containing information files about the 64th memory block in NUMA node 0.
Previously, code that gathered total physical memory by looking at these subdirectories was using a simple glob on `memory*` to determine those memory block subdirectories. However, in some recent Linux kernels a `/sys/devices/system/memory/memory_failure` file causes that simple glob to backfire. This patch replaces the simple glob with a read of the `/sys/devices/system/memory` or `/sys/devices/system/node/nodeX` directory and regex matches on …
> only process memory cell/block subdirs in sysfs

- README.md
- pkg/net/net.go
- pkg/net/net_linux.go
- pkg/net/net_linux_test.go
- pkg/util/util.go
- pkg/util/util_test.go
Added the following to the `NIC` struct:
* `Speed`
* `Duplex`
* `SupportedLinkModes`
* `SupportedPorts`
* `SupportedFECModes`
* `AdvertisedLinkModes`
* `AdvertisedFECModes`
Refactoring PR #335
> Add more fields to NIC

- README.md
- pkg/block/block_test.go
- pkg/cpu/cpu.go
- pkg/cpu/cpu_linux.go
Reworks the way that ProcessorCore structs are determined on Linux by breaking up the long `processorsGet` function into smaller functions and using standard maps for looking up Processor and logicalProcessor structs.
Removes the `ProcessorCore.Index` field entirely, since it was confusing and did not actually represent anything useful. Added clarity to the documentation about `ProcessorCore.LogicalProcessors` and how those numbers are actually the zero-based index of processors on the host and are sometimes called "thread siblings" and that zero-based index of logical processor IDs has nothing to do with the core ID.
Fixes Issue #345
> linux: refactor ProcessorCore retrieval

- go.mod
- go.sum
- pkg/marshal/marshal.go
Hi :wave: 
The `github.com/ghodss/yaml` package is no longer actively maintained. There are numerous inquiries about the project's status on its issue tracker: https://github.com/ghodss/yaml/issues.
Since we are only using the `JSONToYAML` from `github.com/ghodss/yaml`, we can implement the code ourselves [^1] and remove an extra dependency.
---
Alternatively, we can replace `github.com/ghodss/yaml` with `sigs.k8s.io/yaml`, which is a permanent fork currently maintained by Kubernetes SIG. Please let me know if you prefer using a package for YAML unmarshalling, and I will gladly update this pull request.
[^1]: https://github.com/ghodss/yaml/blob/0ca9ea5df5451ffdf184b4428c902747c2c11cd7/yaml.go#L45-L61
> marshal: replace `github.com/ghodss/yaml` with `gopkg.in/yaml.v2`

- README.md
- pkg/pci/pci.go
- pkg/pci/pci_linux.go
- pkg/pci/pci_test.go
Mostly documentation cleanups, but this commit does remove a number of deprecated fields and functions:
* `ghw.PCIInfo.Classes` (deprecated for >1 year, use pcidb instead)
* `ghw.PCIInfo.Products` (deprecated for >1 year, use pcidb instead)
* `ghw.PCIInfo.Vendors` (deprecated for >1 year, use pcidb instead)
* `ghw.PCIInfo.ListDevices()` (deprecated for >1 year, use `ghw.PCIInfo.Devices`)
* `ghw.pkg/pci.Address` (deprecated for >1 year, just use pkg/pci/address package)
* `ghw.pkg/pci.AddressFromString()` (deprecated for >1 year, just use pkg/pci/address package)
Primary documentation changes were to move the configuration options, environment-setting instructions, serialization and snapshot stuff into an "Advanced Usage" section towards the bottom of the README and focus the main "Usage" …
> remove deprecated fields/functions, clean up docs

- README.md
- cmd/ghw-snapshot/main.go
- pkg/block/block_linux.go
- pkg/block/block_linux_test.go
- pkg/block/block_test.go
- pkg/cpu/cpu_linux.go
- pkg/gpu/gpu_linux.go
- pkg/gpu/gpu_linux_test.go
- pkg/linuxdmi/dmi_linux.go
- pkg/memory/memory_cache_linux.go
- pkg/memory/memory_linux.go
- pkg/net/net_linux.go
- pkg/option/option.go
- pkg/pci/pci_linux.go
- pkg/snapshot/clonetree.go
- pkg/snapshot/clonetree_block_linux.go
- pkg/snapshot/clonetree_linux.go
- pkg/snapshot/clonetree_linux_test.go
- pkg/snapshot/clonetree_pci_linux.go
- pkg/snapshot/pack_test.go
- pkg/snapshot/unpack.go
- pkg/snapshot/unpack_test.go
- pkg/topology/topology_linux.go
- pkg/util/util.go
Don't use anymore long-reprecated functions,
switching to recommended alternatives.
No intended changes in behavior.
Fixes lint issues post merging of #350 : https://github.com/jaypipes/ghw/actions/runs/5619500764
> go: chore: remove references to io/ioutil

- README.md
- alias.go
- pkg/block/block.go
- pkg/block/block_darwin.go
- pkg/block/block_linux.go
- pkg/block/block_windows.go
- pkg/cpu/cpu_linux.go
- pkg/memory/memory.go
- pkg/memory/memory_cache.go
- pkg/memory/memory_cache_linux.go
- pkg/memory/memory_linux.go
- pkg/net/net.go
- pkg/net/net_linux.go
- pkg/net/net_windows.go
doc and const cleanup for net package
Ensures proper docstrings for all exported things in the `net`
package and deprecates the (non-Go-idiomatic) ALL_CAPS constants in
favour of CamelCase constants.
doc and const cleanup for block package
Ensures proper docstrings for all exported things in the `block`
package and deprecates the (non-Go-idiomatic) ALL_CAPS constants in
favour of CamelCase constants.
Also officially deprecates the `pkg/block.Info.TotalPhysicalBytes` field
in favour of a `pkg/block.Info.TotalSizeBytes` field (had a TODO in
there a while to do this...).
ensure ProcessorCore.LogicalProcessors sorted
Ensures that we sort the `ProcessorCore.LogicalProcessors` slice of ints
for each processor core in Linux.
Also update the documentation for the CPU package to mark the …
> doc and const cleanup for cpu, block, memory, and net packages

- pkg/block/block_linux.go
The properties that are currently used are not always accurate, for example we have seen that they sometimes contain the WWN and not the serial. This change uses SCSI_IDENT_SERIAL and ID_SCSI_SERIAL first. This behavior aligns with what lsblk does:
https://github.com/util-linux/util-linux/blob/36c52fd14b83e6f7eff9a565c426a1e21812403b/misc-utils/lsblk-properties.c#L122-L128
> Change udev properties for Linux disk serial

- pkg/block/block.go
- pkg/block/block_darwin.go
- pkg/block/block_linux.go
- pkg/block/block_windows.go
Provide a way to get the disk WWN without the vendor extension.
[Ironic root device hints](https://docs.openstack.org/ironic/latest/install/advanced.html#specifying-the-disk-for-deployment-root-device-hints) support matching separately on the WWN, vendor extension, and WWN+extension. This makes it useful to be able to separate the vendor extension from the base WWN.
> Allow separating the WWN vendor extension

- pkg/cpu/cpu_darwin.go
- pkg/cpu/cpu_stub.go
init darwin cpu support! Dev/ran on M1 Max and manually tested the sysctl commands on intel 
Thanks!
> init darwin cpu support

- pkg/pci/address/address.go
- pkg/pci/address/address_test.go
Allow parsing of PCI addresses like `10001:80:05.0` where the domain component is longer than 4 digits.
The domain component should be able to handle values up to 32 bits - see: https://patches.dpdk.org/project/dpdk/patch/20200512133057.106374-1-dariusz.stojaczyk@intel.com/
Fixes #372
> Fix parsing of PCI domains longer than 4 digits

- pkg/memory/memory.go
- pkg/memory/memory_linux.go
- pkg/memory/memory_test.go
- pkg/topology/topology_linux_test.go
https://github.com/jaypipes/ghw/issues/371 fix
Add huge page info to Topology and Memory functionality.
> add HugePage info to memory and topology

- .github/workflows/fmtcheck.yml
- .github/workflows/lint.yml
- .github/workflows/test.yml
The step security Github Action step was stuck and not letting the
workflow proceed. Step Security advised updating to the latest
harden-runner version.
Issue step-security/harden-runner#466
> update Step Security hardener action

- README.md
- pkg/cpu/cpu.go
- pkg/cpu/cpu_linux.go
- pkg/cpu/cpu_linux_test.go
- pkg/cpu/cpu_test.go
- pkg/cpu/cpu_windows.go
- pkg/topology/topology_test.go
All other fields that contain a total amount of something begin with the word `Total` except for the `pkg/cpu.Processor.NumCores` and `NumThreads` fields. This commit adds new fields to `pkg/cpu.Processor` called `TotalCores` and `TotalHardwareThreads` to bring the names of these fields in-line with all other amount/total fields.
In addition, adds a `TotalHardwareThreads` field to the `pkg/cpu.Info` struct and deprecates the less-explicit `TotalThreads` field.
I'd like to remove the now-deprecated `NumThreads`, `NumCores`, and `TotalThreads` fields before we get to a `v.1.0` series.
> use TotalXXX instead of NumXXX

- alias.go
- pkg/gpu/gpu_linux.go
- pkg/pci/pci.go
- pkg/pci/pci_linux.go
- pkg/topology/topology.go
- pkg/topology/topology_linux.go
- pkg/topology/topology_test.go
- pkg/topology/topology_windows.go
Updates the `ARCHITECTURE_SMP` and `ARCHITECTURE_NUMA` constants to `ArchitectureSMP` and `ArchitectureNUMA`, respectively, to align with idiomatic Go naming conventions.
For backwards-compat, keeps `ARCHITECTURE_SMP` and `ARCHITECTURE_NUMA` in the aliased variables for a few releases. These will be discarded when we cut a v1.0 series.
> use Go idiomatic naming for Architecture consts

- cmd/ghw-snapshot/command/create.go
- cmd/ghw-snapshot/command/read.go
- cmd/ghw-snapshot/command/root.go
- cmd/ghw-snapshot/main.go
This is the first step in actually overhauling the ghw library's context package and moving to a more standard `context.Context` usage. In order to standardize the context usage, we needed to change the way that the ghw-snapshot functionality worked to manually construct a `pkg/context.Context` and call `pkg/context.Context:Do()` while reading the snapshot tarball.
In order to do that, I created a new `ghw-snapshot read` command that accepts a single argument to the snapshot tarball path to read:
```
➜  ghw git:(overhaul-snapshot) ✗ GHW_DISABLE_WARNINGS=1 go run cmd/ghw-snapshot/main.go read testdata/snapshots/linux-amd64-intel-xeon-L5640.tar.gz
block storage (8 disks, 723GB physical storage)
cpu (2 physical packages, 12 cores, 24 hardware threads)
gpu (0 graphics cards)
memory (66GB …
```
> overhaul ghw-snapshot tool

- pkg/cpu/cpu_linux.go
- pkg/cpu/cpu_linux_test.go
In ARM  systems, the `/proc/cpuinfo` file does not contain `vendor_id` fields. In the `lscpu` tool, the `CPU implementor` code and a lookup table are used to provide a human-readable vendor name [1].
When running on ARM systems, populate the `CPU.Info.Processors[*].Vendor` field with the "ARM" string.
[1] https://github.com/util-linux/util-linux/pull/564
> Populate `Vendor` field for ARM cpus

- .github/workflows/test.yml
per https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories the oldest support  macos version is nowadays 13,
so use it instead of no longer available v12.
In addition, bump the golang version on macos to a more respectable 1.21 instead of ancient 1.18
(see also: https://github.com/jaypipes/ghw/pull/397)
> gh action: update macos lane

- .github/workflows/fmtcheck.yml
- .github/workflows/lint.yml
- .github/workflows/test.yml
we want to support most 3 recent golang versions
on modern platform and the most modern golang version available on legacy platforms, so let's bump the
versions accordingly
> ci: golang: rotate the most 3 recent supported versions

- pkg/snapshot/pack.go
- filepath.Rel to find relative path in platform aware way.
- file closing by defer.
> fix: Replace strings.TrimPrefix with filepath.Rel

- pkg/snapshot/pack.go
- Replaced os.Stat call and os.Create with os.OpenFile with O_EXCL to avoid TOCTOU.
- Improved logic to handle file size check only when the file exists.
> fix: Refactor OpenDestination func

- pkg/cpu/cpu_darwin.go
Crashing thread - found in https://github.com/docker/for-mac/issues/7588
```
panic: runtime error: index out of range [1] with length 1
goroutine 1124 [running]:
github.com/jaypipes/ghw/pkg/cpu.populateSysctlOutput()
github.com/jaypipes/ghw@v0.13.0/pkg/cpu/cpu_darwin.go:87 +0x204
github.com/jaypipes/ghw/pkg/cpu.(*Info).load(0x14001c11260)
github.com/jaypipes/ghw@v0.13.0/pkg/cpu/cpu_darwin.go:17 +0x20
github.com/jaypipes/ghw/pkg/context.(*Context).Do(0x1400038c780, 0x14001f21c58) 
github.com/jaypipes/ghw@v0.13.0/pkg/context/context.go:125 +0x78
github.com/jaypipes/ghw/pkg/cpu.New({0x0?, 0x14000e14100?, 0x2?})
```
> fixed an out of range index access

- go.mod
- go.sum
- pkg/accelerator/accelerator_linux.go
golang 1.21.z already features `slices.Contains`
(see: https://pkg.go.dev/slices@go1.21.13#Contains) so we can use the stdlib instead of adding a depenency just for a single function.
No intended change in behavior.
> deps: accelerator: remove deps

- pkg/gpu/gpu_linux.go
Ensure we take only the last PCI address in the `/sys/class/drm` sysfs output as the PCI Address of the graphics card. For some graphics cards, they are on a PCI bridge or host bus adapter that was erroneously being identified as the PCI Address of the graphics card itself.
Consider this `ll /sys/class/drm` output on one of my workstations:
```
lrwxrwxrwx 1 root root    0 Mar  9 17:57 card0 -> ../../devices/pci0000:00/0000:00:02.0/drm/card0
lrwxrwxrwx 1 root root    0 Mar  9 17:57 card0-DP-1 -> ../../devices/pci0000:00/0000:00:02.0/drm/card0/card0-DP-1
lrwxrwxrwx 1 root root    0 Mar  9 17:57 card0-HDMI-A-1 -> ../../devices/pci0000:00/0000:00:02.0/drm/card0/card0-HDMI-A-1
lrwxrwxrwx 1 root root    0 Mar  9 17:57 card0-HDMI-A-2 -> …
```
> fix PCI address in filepath for graphics cards

- pkg/block/block_linux.go
Device Mapper devices have `DM_WWN` set in udev in place of `ID_WWN_WITH_VENDOR_EXTENSION`. Reading `DM_WWN` allows us to see the WWN for multipath fibre channel or iSCSI block devices.
Because `DM_WWN` contains the vendor extension, there is no corresponding change to `WWNNoExtension`.
> Get WWN for multipath block devices

- pkg/gpu/gpu_linux.go
- pkg/linuxpath/path_linux_test.go
PCI addresses in `/sys/class/drm` sysfs contains hexadecimal digits. This fix replaces `\d` with `[[:xdigit:]]` in PCI address parser regexp.
Closes #411.
> fix: gpu path parsing on linux

- pkg/gpu/gpu_windows.go
- pkg/memory/memory_linux.go
- pkg/snapshot/pack.go
Replaced strings.Replace with updated strings.ReplaceAll
Use filepath.Ext for file extension instead of strings.HasSuffix.
> Improve string and file extension handling: ReplaceAll & filepath.Ext

- pkg/option/option.go
- pkg/option/option_test.go
- pkg/pci/pci.go
- pkg/pci/pci_linux.go
Ghw doesn't allow to pass options to pcidb, So I added the possibility to pass a custom istance
> Allow to pass a custom instance of pcidb

- pkg/block/block_linux.go
**Problem**
Starting with RHCOS 4.19 (possibly other newer kernels), optical drives and some loop devices report rotational=0, causing them to be misclassified as SSD.
RHCOS 4.19+:
```
lsblk -d -o name,rota
NAME  ROTA
loop0    0
loop1    0  
sda      1
sr0      0  ← CD-ROM incorrectly becomes SSD
```
RHCOS <= 4.18:
```
lsblk -d -o name,rota
NAME  ROTA
loop0    0
loop1    1
sda      1
sr0      1  ← CD-ROM correctly stays ODD
```
**The fix**
Only promote devices to SSD when they're actually HDD type devices
This is likely a general kernel behavior change, not RHCOS only, so the fix benefits all Linux distributions.
**Possible impact**
sr0 stays ODD (fixes the core issue)
loop stays Virtual
Non-rotational sd*/vd*/hd*/xvd* still can be promoted to  SSD
nvme*/mmc* unchanged
> fix: only mark non-rotational HDDs as SSD
